### ISSUE TITLE
TypeError: element.timepicker is not a function

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [Recras/angular-jquery-timepicker#32] opened 2016-04-21 07:14 UTC
Am getting this TypeError: element.timepicker is not a function while using your time picker

**Comment by nederdirk** [comment] 2016-04-21 07:16
unfortunately, due to the terseness of your bug report, we cannot reproduce this problem now. Could you please help us pinpoint this problem by reproducing it on https://plnkr.co/ and sharing that result?

**Comment by KalaiselvanMahendran** [comment] 2016-04-21 07:33
where i can get your library file or cdn in plunker

**Comment by nederdirk** [comment] 2016-04-21 07:38
Current version (0.11) can be referenced via https://cdn.rawgit.com/Recras/angular-jquery-timepicker/0.11.0/src/timepickerdirective.js (non-minified version, I'd suggest using the `...min.js`-version in production

**Comment by KalaiselvanMahendran** [comment] 2016-04-21 07:51
please checkout this [http://plnkr.co/edit/QzqHgnVxA0J0BKX6vdT8?p=preview](http://plnkr.co/edit/QzqHgnVxA0J0BKX6vdT8?p=preview)

**Comment by nederdirk** [comment] 2016-04-21 08:02
I'm sorry, the problem you encounter seems to stem from the fact that you haven't loaded jquery-timepicker at the time of app initialization (not at all in your plunker)
I'm closing this issue for now. Feel free to re-open this issue if you can demonstrate this is really a bug in `angular-jquery-timepicker`

**Closed by nederdirk** 2016-04-21 08:02 UTC
